# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-18 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0002_auto_20181118_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='content',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=2),
        ),
        migrations.AlterField(
            model_name='project',
            name='creativity',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=2),
        ),
        migrations.AlterField(
            model_name='project',
            name='design',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=2),
        ),
        migrations.AlterField(
            model_name='project',
            name='overall_score',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=2),
        ),
        migrations.AlterField(
            model_name='project',
            name='usability',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=2),
        ),
    ]
