# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-18 20:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0005_auto_20181118_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='avatar',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='avatars/'),
            preserve_default=False,
        ),
    ]
